development:
  secret_key_base: super_long_secret_key_for_development
  google_client_id: 7993178126-74rf82eo9jvh0h1hojuvo3p3fmh7daf1.apps.googleusercontent.com
  google_client_secret: 2r0AEoJQUw5ooHfvjpA_KMqk